<!-- Navigation -->


<!-- Masthead -->

<header class="masthead4">
    <div class="row    ">
        <div class="container">

            <form method="POST" id="formLogin" action="/#main" class="form-horizontal" role="form">
                <div class="col-lg-9">
                    <div class="input-group">
                        <select class="custom-select text-white" id="city" name="city">
                            <option value="1" >CANANEIA</option>
                            <option value="4">ILHA COMPRIDA</option>
                            <option value="2">IGUAPE</option>
                            <option value="3">PARIQUERA - AÇU</option>
                        </select>
                        <select class="custom-select text-white" id="category" name="category">

                            <option value="1" >NATUREZA E CULTURA</option>
                            <option value="3">ROTEIROS E PASSEIOS</option>
                            <option value="4">HOSPEDAGEM</option>
                            <option value="5">GASTRONOMIA</option>
                            <option value="6">AGENDA DE EVENTOS</option>
                            <option value="8">SERVIÇOS</option>
                        </select>
                        <div class="input-group-append text-white">
                            <button class="btn btn-outline-secondary text-white send" onclick="myFunction()" type="submit">Pesquisar</button>

                        </div>
                    </div>
                </div>
            </form>


        </div>
    </div>
</header>

<section >



    <header class="masthead2" id="main">
    <div class="container">
        <br>
        <!-- Stack the columns on mobile by making one full-width and the other half-width -->
        <div class="row">
            <div class=" col-md-12">
                <?php foreach ($this->view->objetos[0]['empresa'] as $content): ?>
                <h1><?= $content['title']; ?></h1>
                <strong><?= $content['desc']; ?> </strong>
                <?php endforeach; ?>
            </div>

        </div>

        <div class="row">
            <div class=" col-md-5">
                <br><br>
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <?php foreach ($this->view->objetos[0]['imgs'] as $content): ?>
                            <div class="carousel-item active">
                                <img class="img-slider" src="<?= 'http://img.cananeiaclassificados.com.br/atrativos/imagens/' . $content['file'] ?>" alt="First slide">
                            </div>
                        <?php endforeach; ?>

                    </div>
                </div>

            </div>
            <div class=" col-md-7">

                <br><br>
                <?php foreach ($this->view->objetos[0]['empresa'] as $content): ?>
                    <p><?= $content['content'] ?></p>
                <?php endforeach; ?>

            </div>

        </div>
        <br>
        <?php foreach ($this->view->objetos[0]['empresa'] as $content): ?>
            <p><strong>Forma de acesso:</strong> <?= $content['forma_acesso'] ?></p>
        <?php endforeach; ?>

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d28925.104164037337!2d-47.9489446522698!3d-25.01241307885567!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94dae569d14df881%3A0xd4450a499dcee6a4!2sCanan%C3%A9ia%2C+SP%2C+11990-000!5e0!3m2!1spt-BR!2sbr!4v1554512746256!5m2!1spt-BR!2sbr" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
        <br>
    </div>

    </header>
</section>

