

<!-- Masthead -->

<header class="masthead4">

    <div class="row    ">
        <div class="container">

            <form method="POST" id="formLogin" action="/#main" class="form-horizontal" role="form">
                <div class="col-lg-9">
                    <div class="input-group">
                        <select class="custom-select text-white" id="city" name="city">
                            <option value="1" >CANANEIA</option>
                            <option value="4">ILHA COMPRIDA</option>
                            <option value="2">IGUAPE</option>
                            <option value="3">PARIQUERA - AÇU</option>
                        </select>
                        <select class="custom-select text-white" id="category" name="category">

                            <option value="1" >NATUREZA E CULTURA</option>
                            <option value="3">ROTEIROS E PASSEIOS</option>
                            <option value="4">HOSPEDAGEM</option>
                            <option value="5">GASTRONOMIA</option>
                            <option value="6">AGENDA DE EVENTOS</option>
                            <option value="8">SERVIÇOS</option>
                        </select>
                        <div class="input-group-append text-white">
                            <button class="btn btn-outline-secondary text-white send" onclick="myFunction()" type="submit">Pesquisar</button>

                        </div>
                    </div>
                </div>
            </form>


        </div>
    </div>

</header>

<section >

    <header class="masthead2" id="main">
    <div class="container">
        <br>
        <!-- Stack the columns on mobile by making one full-width and the other half-width -->
        <div class="row">
            <div class=" col-md-12">
                <h1><?= $this->view->objetos['nome_subcategory']; ?> em <?= $this->view->objetos['city']; ?></h1>
            </div>
        </div>

        <?php foreach ($this->view->objetos['data'] as $content): ?>

        <div class="row" id="santa-maria">
            <div class=" col-md-12">
                <h3><?=  $content['title'] ?></h3>
                <br>
            </div>

        </div>
        <div class="row">
            <div class=" col-md-4">
                <img class="img-fluid" src="<?= 'http://img.cananeiaclassificados.com.br/atrativos/logo/' . $content['logoPath'] ?>">
            </div>
            <div class=" col-md-8">
                <strong><?=  $content['desc'] ?></strong>
                <br><br>
                <p><?=  substr($content['content'] , 0,180 )?> [...]</p>
                <p><strong>Localizado em: <?=  $content['location'] ?></strong></p>
                <a href="/content-full?id=<?=  $content['id'] ?>" class="btn btn-success" role="button">Explorar</a>
                <hr>

            </div>

        </div>

        <br>
            <?php endforeach; ?>

<!--        <div class="row">-->
<!--        <div class="col-md-5"></div>-->
<!--        <div class="col-md-6"><nav aria-label="Navegação de página exemplo">-->
<!--                <ul class="pagination">-->
<!--                    <li class="page-item"><a class="page-link" href="#">Anterior</a></li>-->
<!--                    <li class="page-item"><a class="page-link" href="#">1</a></li>-->
<!--                    <li class="page-item"><a class="page-link" href="#">2</a></li>-->
<!--                    <li class="page-item"><a class="page-link" href="#">3</a></li>-->
<!--                    <li class="page-item"><a class="page-link" href="#">Próximo</a></li>-->
<!--                </ul>-->
<!--            </nav></div>-->
<!--    </div>-->

    </div>

</section>