
<!-- Masthead -->
<header class="masthead">

    <div class="row  align-items-start front-box-top mr-n10">
        <div class="container">

            <form method="POST" id="formLogin" action="/#main" class="form-horizontal" role="form">
                <div class="col-lg-9">
                    <div class="input-group">
                        <select class="custom-select text-white" id="city" name="city">
                            <option value="1" >CANANEIA</option>
                            <option value="4">ILHA COMPRIDA</option>
                            <option value="2">IGUAPE</option>
                            <option value="3">PARIQUERA - AÇU</option>
                        </select>
                        <select class="custom-select text-white" id="category" name="category">

                            <option value="1" >NATUREZA E CULTURA</option>
                            <option value="3">ROTEIROS E PASSEIOS</option>
                            <option value="4">HOSPEDAGEM</option>
                            <option value="5">GASTRONOMIA</option>
                            <option value="6">AGENDA DE EVENTOS</option>
                            <option value="8">SERVIÇOS</option>
                        </select>
                        <div class="input-group-append text-white">
                            <button class="btn btn-outline-secondary text-white send" onclick="myFunction()" type="submit">Pesquisar</button>

                        </div>
                    </div>
                </div>
            </form>



            <br><br><br>
            <div class="col-lg-5 ">
                <img src="http://guialagamar.tur.br/img/marca-guia-lagamar2.png" class="img-fluid text-left teste">
                <p class="text-left roboto-Light text-white">Conectamos pessoas a lugares, roteiros e experiências únicas em meio a maior e mais belo trecho de Mata Atlântica do planeta.</p>
                <div class="row ">
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Download</a>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Download</a>
                </div>
            </div>
        </div>
    </div>

</header>

<header class="masthead2" id="main">
    <div class="row  col-lg-12  justify-content-center text-center">
        <h3 class="boder1 "><?= $this->view->objetos['category_name'] ?> EM <?= $this->view->objetos['city_name'] ?></h3>

    </div>

    <div class="container h-100">
        <div class="row">
            <?php foreach ($this->view->objetos['result'] as $data): ?>
                <div class="col-lg-4 align-self-end">
                    <div class="card" style="width: 18rem;" >
                        <a href="content?city=<?= $data['cityId'] ?>&category=<?= $data['id'] ?> ">
                            <img class="card-img-top" src="<?= 'http://img.cananeiaclassificados.com.br/images/subcategory/'.$data['imagem']?>" alt="Card image cap">
                        </a>


                        <div class="card-body">
                            <a href="content?city=<?= $this->view->objetos['cityId'] ?>&category=<?= $data['id'] ?> ">
                                <h5 class="card-title text-center"><?= $data['nome_subcategory'] ?></h5>
                            </a>

                        </div>
                    </div>
                    <br>
                </div>

            <?php endforeach ?>

        </div>


        <h4>Dê play e conheça nossas maravilhas</h4>


    </div>
</header>

<section class="video">
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="./video/Drone Phantom 3 - Voo sobre Cananeia.mp4"></iframe>
    </div>

</section>

<header class="masthead3">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <br> <br>
                <img src="http://guialagamar.tur.br/img/marca-guia-lagamar2.png" class="img-fluid">
            </div>

        </div>
    </div>
</header>



