

<!-- Masthead -->

<header class="masthead4">

    <div class="row    ">
        <div class="container">

            <form method="POST" id="formLogin" action="/#main" class="form-horizontal" role="form">
                <div class="col-lg-9">
                    <div class="input-group">
                        <select class="custom-select text-white" id="city" name="city">
                            <option value="1" >CANANEIA</option>
                            <option value="4">ILHA COMPRIDA</option>
                            <option value="2">IGUAPE</option>
                            <option value="3">PARIQUERA - AÇU</option>
                        </select>
                        <select class="custom-select text-white" id="category" name="category">

                            <option value="1" >NATUREZA E CULTURA</option>
                            <option value="3">ROTEIROS E PASSEIOS</option>
                            <option value="4">HOSPEDAGEM</option>
                            <option value="5">GASTRONOMIA</option>
                            <option value="6">AGENDA DE EVENTOS</option>
                            <option value="8">SERVIÇOS</option>
                        </select>
                        <div class="input-group-append text-white">
                            <button class="btn btn-outline-secondary text-white send" onclick="myFunction()" type="submit">Pesquisar</button>

                        </div>
                    </div>
                </div>
            </form>


        </div>
    </div>

</header>

<section >

    <header class="masthead2" id="main">
        <div class="col-md-12"></div>
        <h1 class="noContent">&#160;&#160;&#160;Nenhum conteúdo encontrado</h1>
        <br><br><br><br><br><br><br><br><br>
        <br><br><br><br>
    </header>



</section>
