
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="editarModalLabel">Encerrar incidente</h4>
    </div>
    <div class="modal-body">
            <form action="/incidentes/edit" method="post" id="formLogin" class="form-horizontal" role="form"
                  data-bv-feedbackicons-valid="glyphicon glyphicon-ok"
                  data-bv-feedbackicons-invalid="glyphicon glyphicon-remove"
                  data-bv-feedbackicons-validating="glyphicon glyphicon-refresh"
                >
                <input type="hidden" name="id" value="<?php echo $this->view->objetos['id'] ?>">
                
                <div  class="form-cadastro">
                    <h4><i class="glyphicon glyphicon-user"></i> Ecerrar incidente </span></h4>
                    <hr>
                 
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Descrição<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <textarea name="descricao" placeholder="Descrição" class="form-control"
                                      data-bv-notempty="true"
                                      row ="2"
                                      data-bv-notempty-message="Por favor informe a Descrição!"
                                     
                                       ><?php echo $this->view->objetos['descricao'] ?></textarea>
                        </div>
                    </div>

                   <div class="form-group">
                   <label class="col-sm-2 control-label">Status<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                                    <select class="form-control"  id="status" name="status">                                        
                                        <option value="Aberto" <?php echo ($this->view->objetos['status'] ==  'Aberto') ? ' selected="selected"' : '';?>>Aberto</option>
                                        <option value="Fechado" <?php echo ($this->view->objetos['status'] ==  'Fechado') ? ' selected="selected"' : '';?>>Fechado</option>
                                                                         
                                    </select>
                        </div>  
                        </div>  

                    <div class="form-group">
                    <label class="col-sm-2 control-label"></span></label>                       
                        <div class="col-sm-9 text-right">
                            <br>
                        <button type="submit" class="btn btn-principal " >Salvar</button> 
                        </div>  
                   </div>  

                   
                </div>
            </form>
            <p></p>
    </div>