
<div class="content col-md-12" id="eventContent">
    <h3>Incidentes</h3>
     <br>
        <a href="#" class="btn-principal btn btn-primary"  data-toggle="modal" data-target="#adicionarModal">Abrir incidentes</a> 
     <br>

    <table class="table table-bordered table-hover ">
            <thead>
                <tr>       
                    <th>#</th>       
                    <th>Atendente</th>        
                    <th>Cliente</th>
                    <th>Descricao</th>
                    <th>Status</th>
                    <th>Abertura</th>      
                    <th width="10%" align="center">Encerrar incidente</th>
                </tr>
            </thead>

            <tbody>

                    <?php foreach ($this->view->objetos as $registro): ?>
                            <tr>            
                                <td align="left"><?= $registro['id']; ?></td>             
                                <td align="left"><?= $registro['atendente_nome']; ?></td>             
                                <td align="left"><?= $registro['cliente_nome']; ?></td>
                                <td align="left"><?= $registro['descricao']; ?></td>
                                <td align="left"><?= $registro['status']; ?></td>
                                <td align="left"><?= $registro['creation_time']; ?></td>
                                
                                <td>
                                    <div class="text-center"> 
                                        <a href="/incidentes/show?id=<?=$registro['id'];?>" data-toggle="modal" data-target="#editarModal-<?=$registro['id'];?>">
                                            <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                                        </a>
                                    </div>                   
                                </td>

                            </tr>

                            <!-- Editar Modal -->
                            <div class="modal fade" id="editarModal-<?=$registro['id'];?>" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="editarModalLabel">Editar incdente</h4>
                                        </div>

                                    </div>
                                </div>
                            </div>                      
                    <?php endforeach; ?>
            </tbody>
    </table>

    <!-- paginação -->
    <div class="text-center"> 
        <ul class="pagination">
            <li><a href="incidentes?pagina=1">1</a></li>
            <li ><a href="incidentes?pagina=2">2</a></li>
            <li><a href="incidentes?pagina=3">3</a></li>
            <li><a href="incidentes?pagina=4">4</a></li>
            <li><a href="incidentes?pagina=5">5</a></li>
            <li><a href="incidentes?pagina=6">6</a></li>
            <li><a href="incidentes?pagina=7">7</a></li>
            <li><a href="incidentes?pagina=8">8</a></li>
            <li><a href="incidentes?pagina=9">9</a></li>
            <li><a href="incidentes?pagina=10">10</a></li>
        </ul> 
    </div>
    <!-- fim paginação -->
             
    <!-- Adicionar Modal -->
    <div class="modal fade" id="adicionarModal" tabindex="-1" role="dialog" aria-labelledby="adicionarModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="adicionarModalLabel">Adicionar incidentes</h4>
                                    
                        <form method="post" id="formLogin" action="/incidentes/novo" class="form-horizontal" role="form">
                            <div class="container col-md-12">
                                <div class="form-group">
                                        <label class="">Clientes</label>
                                        <select class="form-control" id="cliente" name="cliente">                                       
                                            <option value="1">Jefferson</option>
                                            <option value="2">Máximo</option>
                                            <option value="3">Gabriella</option>                                        
                                        </select>
                                    </div>  
                                    
                                    <div class="form-group">
                                        <label class="">Status</label>
                                        <select class="form-control"  id="status" name="status">                                        
                                            <option value="Aberto">Aberto</option>
                                            <option value="Fechado">Fechado</option>                                                                         
                                        </select>
                                    </div>  
                                
                                    <div class="form-group">
                                        <label class="">  Descrição</label>
                                        <textarea  name="descricao" class="form-control"  class="form-control" rows="2" id="comment"></textarea>
                                    </div> 
                                
                                    <input type ="hidden" id="atendente" name="atendente" value = "4">
                                            
                                    <div class="form-group text-right">
                                        <div class="col-sm-12" style="padding-right:20px;">
                                            <button type="submit" class="btn-principal btn btn-primary">Salvar</button>
                                        </div>
                                    </div>
                            </div>
                    </form> 
                </div>
            </div>
        </div>
    </div>
    
</div>


